#!/bin/sh

# GIT_ID=`git rev-parse HEAD`
GIT_ID=`git describe --always`
GIT_NUM=`git rev-list HEAD --count`
DATE=`date +%Y-%b-%d`
DNUM=`date +%Y%m%d`

(cat <<EOF
__all__ = ['version']


class version:
    """Current version."""
    v_short = 'DNUM.GIT_NUM.GIT_ID'
    v_long = 'GIT_ID (DATE)'
    v_gnu = 'miles GIT_ID (DATE)'
EOF
) | sed -e "s/GIT_ID/$GIT_ID/g" -e "s/DATE/$DATE/g" -e "s/DNUM/$DNUM/g" -e "s/GIT_NUM/$GIT_NUM/g"

echo "miles $DNUM.$GIT_NUM.$GIT_ID $GIT_ID ($DATE)" >&2
